//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FF3LE.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"C:\\\\\"")]
        public string LastRomPath {
            get {
                return ((string)(this["LastRomPath"]));
            }
            set {
                this["LastRomPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>World of Balance, World Map</string>\r\n  <string>World of Ruin, World Map</" +
            "string>\r\n  <string>Serpent Trench, World Map</string>\r\n  <string>\"On that day..." +
            "\" etc.</string>\r\n  <string>Shadow\'s Dream 1</string>\r\n  <string>Mog\'s Explanatio" +
            "n</string>\r\n  <string>Blackjack, Deck</string>\r\n  <string>Blackjack, Inside</str" +
            "ing>\r\n  <string>Blackjack, Back Room</string>\r\n  <string>Choose A Scenario</stri" +
            "ng>\r\n  <string>Blackjack, Roof</string>\r\n  <string>Falcon, Roof</string>\r\n  <str" +
            "ing>Falcon, Main Room</string>\r\n  <string>Falcon, Roof, Landing on Kefka\'s Tower" +
            "</string>\r\n  <string>Chocobo Stable, Forested (WOB)</string>\r\n  <string>Chocobo " +
            "Stable, Forested Inside</string>\r\n  <string>Chocobo Stable, Forested (WOR)</stri" +
            "ng>\r\n  <string>Falcon, Roof</string>\r\n  <string>Narshe Cliff, Intro</string>\r\n  " +
            "<string>Narshe, Outside, Beginning (WOB)</string>\r\n  <string>Narshe, Outside (WO" +
            "B)</string>\r\n  <string>Narshe, Outside, Beginning (WOB)</string>\r\n  <string>Nars" +
            "he, Outside, Battlefield (WOB)</string>\r\n  <string>Narshe, Outside, Northern Cli" +
            "ff (WOB)</string>\r\n  <string>Narshe, Weapons Shop (WOR)</string>\r\n  <string>Nars" +
            "he, Armor Shop (WOR)</string>\r\n  <string>Narshe, Item Shop (WOR)</string>\r\n  <st" +
            "ring>Narshe, Relics Shop (WOR)</string>\r\n  <string>Narshe, Inn (WOR)</string>\r\n " +
            " <string>Narshe, Pub (WOR)</string>\r\n  <string>Narshe, Elder\'s House</string>\r\n " +
            " <string>___Chocobo Stable</string>\r\n  <string>Narshe, Outside (WOR)</string>\r\n " +
            " <string>Narshe, Outside, North (WOR)</string>\r\n  <string>Narshe, Outside, Battl" +
            "efield (WOR)</string>\r\n  <string>Narshe, Outside, Northern Cliff (WOR)</string>\r" +
            "\n  <string>Narshe, Mines Cart Rail Rooms (WOR)</string>\r\n  <string>Narshe, Mines" +
            " Battle Room (WOR)</string>\r\n  <string>Narshe, Mines 1 (WOR)</string>\r\n  <string" +
            ">Narshe, Outside, North, Beginning</string>\r\n  <string>Narshe, Mines 1, Beginnin" +
            "g (WOB)</string>\r\n  <string>Narshe, Mines 1 (WOB)</string>\r\n  <string>Narshe, Mi" +
            "nes Esper Room, Beginning (WOB)</string>\r\n  <string>Narshe, Mines Esper Room, Em" +
            "pty (WOB)</string>\r\n  <string>Narshe, Moogle\'s Room (WOR)</string>\r\n  <string>__" +
            "_</string>\r\n  <string>___</string>\r\n  <string>___</string>\r\n  <string>Narshe, Mi" +
            "nes 2, From Secret (WOB)</string>\r\n  <string>Narshe, Mines Checkpoint (WOB)</str" +
            "ing>\r\n  <string>Narshe, Mines 2 (WOB)</string>\r\n  <string>Narshe, Mines Battle R" +
            "oom (WOB)</string>\r\n  <string>Narshe, Moogle\'s Room (WOB)</string>\r\n  <string>Ca" +
            "ve to Figaro Castle, Room 2</string>\r\n  <string>Figaro Castle, Submerging</strin" +
            "g>\r\n  <string>Figaro Castle, Outside</string>\r\n  <string>Figaro Desert, Kefka &a" +
            "mp; Troops</string>\r\n  <string>Figaro Castle, King\'s Bedroom</string>\r\n  <string" +
            ">Figaro Castle, Throne Room</string>\r\n  <string>Figaro Castle, Inside</string>\r\n" +
            "  <string>Figaro Castle, Library</string>\r\n  <string>Figaro Castle, Basement 1</" +
            "string>\r\n  <string>Figaro Castle, Basement 2</string>\r\n  <string>Figaro Castle, " +
            "Basement 3</string>\r\n  <string>Figaro Castle, Engine Room</string>\r\n  <string>Fi" +
            "garo Castle, Treasure Room</string>\r\n  <string>Figaro Castle, Regal Crown Room</" +
            "string>\r\n  <string>Figaro Castle, Outside, Nighttime</string>\r\n  <string>Cave to" +
            " South Figaro (WOR)</string>\r\n  <string>Cave to South Figaro, Rooms</string>\r\n  " +
            "<string>Cave to South Figaro (WOB)</string>\r\n  <string>Cave to South Figaro, Ent" +
            "rance</string>\r\n  <string>Cave to South Figaro, Room 2</string>\r\n  <string>Cave " +
            "to South Figaro, Room 1</string>\r\n  <string>South Figaro, Outside (WOR)</string>" +
            "\r\n  <string>South Figaro, Outside (WOB)</string>\r\n  <string>South Figaro, Inn/Re" +
            "lics</string>\r\n  <string>South Figaro, Arsenal</string>\r\n  <string>South Figaro," +
            " Pub</string>\r\n  <string>___</string>\r\n  <string>South Figaro, Chocobo Stable</s" +
            "tring>\r\n  <string>South Figaro, Rich Man\'s House</string>\r\n  <string>___</string" +
            ">\r\n  <string>South Figaro, Basement 1</string>\r\n  <string>South Figaro, Basement" +
            " 1 Clock Room</string>\r\n  <string>South Figaro, Item Shop</string>\r\n  <string>So" +
            "uth Figaro, Duncan\'s House</string>\r\n  <string>South Figaro, Basement 1 Monster " +
            "Room</string>\r\n  <string>South Figaro, Basement 1 Save Point</string>\r\n  <string" +
            ">South Figaro, Basement 2</string>\r\n  <string>Cave to Figaro Castle, Entrance (W" +
            "OR)</string>\r\n  <string>South Figaro, Dock (WOR)</string>\r\n  <string>Cave to Fig" +
            "aro Castle, Room 1</string>\r\n  <string>Sabin\'s House, Outside</string>\r\n  <strin" +
            "g>Sabin\'s House, Inside</string>\r\n  <string>Mt.Kolts, Entrance</string>\r\n  <stri" +
            "ng>Mt.Kolts, Outside</string>\r\n  <string>Mt.Kolts, Outside Bridge</string>\r\n  <s" +
            "tring>Mt.Kolts, Outside Vargas Area</string>\r\n  <string>___</string>\r\n  <string>" +
            "Mt.Kolts, Cave</string>\r\n  <string>Mt.Kolts, Exit</string>\r\n  <string>Mt.Kolts, " +
            "Cliffs</string>\r\n  <string>Mt.Kolts, Cave Save Point</string>\r\n  <string>Narshe," +
            " School</string>\r\n  <string>Narshe, School, Adv. Battle Tactics</string>\r\n  <str" +
            "ing>Narshe, School, Battle Tactics</string>\r\n  <string>Narshe, School, Environme" +
            "ntal Science</string>\r\n  <string>Returner\'s Hideout, Entrance</string>\r\n  <strin" +
            "g>Returner\'s Hideout, Inside</string>\r\n  <string>Returner\'s Hideout, Rooms</stri" +
            "ng>\r\n  <string>Returner\'s Hideout, Inn</string>\r\n  <string>Tunnel to Lete River<" +
            "/string>\r\n  <string>Lete River</string>\r\n  <string>Lete River Cave</string>\r\n  <" +
            "string>Gau\'s Father\'s House, Outside</string>\r\n  <string>Gau\'s Father\'s House, I" +
            "nside</string>\r\n  <string>Military Base Camp</string>\r\n  <string>___</string>\r\n " +
            " <string>Military Base Camp 2</string>\r\n  <string>Doma Castle, Outside (WOB)</st" +
            "ring>\r\n  <string>Doma Castle, Outside Poisoning (WOB)</string>\r\n  <string>___</s" +
            "tring>\r\n  <string>Doma Castle, Inside</string>\r\n  <string>Doma Castle, Cyan\'s Ro" +
            "om</string>\r\n  <string>Cyan\'s Dream, Doma Castle, Outside</string>\r\n  <string>Cy" +
            "an\'s Dream, Doma Castle Rooms</string>\r\n  <string>Duncan\'s House, Outside</strin" +
            "g>\r\n  <string>Duncan\'s House, Inside</string>\r\n  <string>Ending, sky with birds<" +
            "/string>\r\n  <string>Ending, Phantom Forest</string>\r\n  <string>Gau\'s Father\'s Ho" +
            "use, Outside (WOR)</string>\r\n  <string>Phantom Forest 1</string>\r\n  <string>Phan" +
            "tom Forest 2</string>\r\n  <string>Phantom Forest 3</string>\r\n  <string>Phantom Fo" +
            "rest 4</string>\r\n  <string>Ending, mountain bridge</string>\r\n  <string>Phantom T" +
            "rain, Docking Station 4</string>\r\n  <string>Phantom Train, Docking Station 2</st" +
            "ring>\r\n  <string>Phantom Train, Docking Station 3</string>\r\n  <string>Phantom Tr" +
            "ain, Docking Station 1</string>\r\n  <string>Phantom Train, Outside 2</string>\r\n  " +
            "<string>Phantom Train, Outside 1</string>\r\n  <string>Cyan\'s Dream, Phantom Train" +
            ", Outside</string>\r\n  <string>Cyan\'s Dream, Phantom Train, Inside</string>\r\n  <s" +
            "tring>Phantom Train, Inside 1</string>\r\n  <string>Phantom Train, Engineer\'s Room" +
            "</string>\r\n  <string>Phantom Train, Restaurant</string>\r\n  <string>Mobliz, Outsi" +
            "de during Light of Judgement</string>\r\n  <string>Phantom Train, Inside 2</string" +
            ">\r\n  <string>Mobliz, Basement 2, After Phunbaba 1</string>\r\n  <string>Phantom Tr" +
            "ain, Inside 3</string>\r\n  <string>Phantom Train, Inside 4</string>\r\n  <string>Ph" +
            "antom Train, Inside Rooms</string>\r\n  <string>Mobliz, Basement 2</string>\r\n  <st" +
            "ring>Waterfall Cave</string>\r\n  <string>Waterfall Cliff</string>\r\n  <string>Mobl" +
            "iz, Outside (WOB)</string>\r\n  <string>Mobliz, Outside (WOR)</string>\r\n  <string>" +
            "Veldt Shore</string>\r\n  <string>Mobliz, Inn</string>\r\n  <string>Mobliz, Arsenal<" +
            "/string>\r\n  <string>Mobliz, Relics</string>\r\n  <string>Mobliz, Mail House</strin" +
            "g>\r\n  <string>Mobliz, Item Shop</string>\r\n  <string>Mobliz, Basement 1</string>\r" +
            "\n  <string>Waterfall Entrance</string>\r\n  <string>Veldt Cave to Waterfall</strin" +
            "g>\r\n  <string>Veldt Waterfall</string>\r\n  <string>Nikeah, Outside</string>\r\n  <s" +
            "tring>Veldt Shore</string>\r\n  <string>Nikeah, Inn</string>\r\n  <string>Nikeah, Pu" +
            "b</string>\r\n  <string>Nikeah, Chocobo Stable</string>\r\n  <string>Shadow\'s Dream " +
            "2, Phantom Forest</string>\r\n  <string>Serpent Trench Cave 1</string>\r\n  <string>" +
            "Mt.Zozo, Outside Bridge</string>\r\n  <string>Mt.Zozo, Outside 1</string>\r\n  <stri" +
            "ng>Mt.Zozo, Outside 2</string>\r\n  <string>Mt.Zozo, Inside</string>\r\n  <string>Mt" +
            ".Zozo, Cyan\'s Room</string>\r\n  <string>Mt.Zozo, Cliff</string>\r\n  <string>Ending" +
            ", Relm, Shadow, Strago</string>\r\n  <string>Mobliz, Basement 2, Before Kefka Figh" +
            "t</string>\r\n  <string>Mobliz, Outside, Before Kefka Fight</string>\r\n  <string>Cr" +
            "azy Man\'s House, Outside</string>\r\n  <string>Crazy Man\'s House, Inside</string>\r" +
            "\n  <string>Nikeah, Ferry (WOB)</string>\r\n  <string>Kohlingen, Outside (WOB)</str" +
            "ing>\r\n  <string>Kohlingen, Outside (WOR)</string>\r\n  <string>Ending, Rapids</str" +
            "ing>\r\n  <string>Kohlingen, Inn (WOR)</string>\r\n  <string>___Kohlingen</string>\r\n" +
            "  <string>___Kohlingen, Arsenal</string>\r\n  <string>Kohlingen, General Store</st" +
            "ring>\r\n  <string>Kohlingen, Chemist\'s House</string>\r\n  <string>Maranda, Flower " +
            "Girl\'s House (WOR)</string>\r\n  <string>Kohlingen, Rachel\'s House</string>\r\n  <st" +
            "ring>Jidoor, Outside</string>\r\n  <string>___nothing</string>\r\n  <string>Jidoor, " +
            "Auction House</string>\r\n  <string>Jidoor, Item Shop</string>\r\n  <string>Jidoor, " +
            "Relics</string>\r\n  <string>Jidoor, Armor Shop</string>\r\n  <string>Jidoor, Weapon" +
            " Shop</string>\r\n  <string>Jidoor, Chocobo Stable</string>\r\n  <string>Jidoor, Inn" +
            "</string>\r\n  <string>Owzer\'s House, Basement</string>\r\n  <string>Owzer\'s House, " +
            "Art Room</string>\r\n  <string>Owzer\'s House, F1</string>\r\n  <string>Ending, Cyan " +
            "1</string>\r\n  <string>Ending, Umaro, Mog 1</string>\r\n  <string>Ending, Gogo 1</s" +
            "tring>\r\n  <string>Ending, Gau 1</string>\r\n  <string>Cliff, Setzer waits for Dari" +
            "ll</string>\r\n  <string>Ending, Falcon flying through sky</string>\r\n  <string>Esp" +
            "er World, Lake</string>\r\n  <string>Esper World, Outside</string>\r\n  <string>Espe" +
            "r World, Gate</string>\r\n  <string>Esper World, House</string>\r\n  <string>___boat" +
            " dock</string>\r\n  <string>Zozo, Outside</string>\r\n  <string>___nothing</string>\r" +
            "\n  <string>___nothing</string>\r\n  <string>___nothing</string>\r\n  <string>Zozo, I" +
            "nside House</string>\r\n  <string>Zozo, Terra\'s Room</string>\r\n  <string>___nothin" +
            "g</string>\r\n  <string>___nothing</string>\r\n  <string>___nothing</string>\r\n  <str" +
            "ing>___nothing</string>\r\n  <string>Opera House, Theater</string>\r\n  <string>Oper" +
            "a House, Switch Room</string>\r\n  <string>Opera House, Theater Play 2</string>\r\n " +
            " <string>Opera House, Theater Play 1</string>\r\n  <string>Opera House, Ceiling</s" +
            "tring>\r\n  <string>Opera House, Castle Balcony</string>\r\n  <string>Opera House, M" +
            "ain</string>\r\n  <string>Opera House, Dressing Room</string>\r\n  <string>___Opera " +
            "House</string>\r\n  <string>Vector, after Magitek Factory</string>\r\n  <string>Impe" +
            "rial Castle, Cranes Activating</string>\r\n  <string>Vector, Outside</string>\r\n  <" +
            "string>Imperial Castle</string>\r\n  <string>Imperial Castle, Outside Roof</string" +
            ">\r\n  <string>Vector, Inn</string>\r\n  <string>Vector, Weapon Shop</string>\r\n  <st" +
            "ring>Vector, Pub</string>\r\n  <string>Vector, Armor Shop</string>\r\n  <string>Vect" +
            "or, Healer\'s House</string>\r\n  <string>Imperial Castle, Inside</string>\r\n  <stri" +
            "ng>Imperial Castle, Banquet</string>\r\n  <string>Imperial Castle, Bedroom</string" +
            ">\r\n  <string>Vector, Outside, Burning</string>\r\n  <string>Ending, Cyan, Mog, Gog" +
            "o 2</string>\r\n  <string>Ending, Setzer</string>\r\n  <string>Ending, Umaro 2</stri" +
            "ng>\r\n  <string>___Magitek Factory</string>\r\n  <string>Ending, Edgar and Sabin</s" +
            "tring>\r\n  <string>Ending, Falcon taking flight from Kefka\'s Tower</string>\r\n  <s" +
            "tring>Ending, Locke and Celes 1</string>\r\n  <string>Ending, Shadow, Strago, Gau " +
            "2</string>\r\n  <string>Magitek Factory, Room 1</string>\r\n  <string>Magitek Factor" +
            "y, Room 2</string>\r\n  <string>Magitek Factory, Room 3 (Espers)</string>\r\n  <stri" +
            "ng>___Magitek Factory</string>\r\n  <string>Magitek Factory, Elevator</string>\r\n  " +
            "<string>___Magitek Factory</string>\r\n  <string>Ending, Terra</string>\r\n  <string" +
            ">Magitek Factory, Room 4</string>\r\n  <string>Magitek Factory, Room 5 (Save)</str" +
            "ing>\r\n  <string>Magitek Res. Facility, Room 1</string>\r\n  <string>Magitek Factor" +
            "y, Minecart Dock</string>\r\n  <string>Magitek Res. Facility, Room 2 (Number 042)<" +
            "/string>\r\n  <string>Magitek Res. Facility, Espers</string>\r\n  <string>___dummied" +
            "</string>\r\n  <string>Zone Eater\'s Stomach, Room 1</string>\r\n  <string>Zone Eater" +
            "\'s Stomach, Room 4</string>\r\n  <string>Zone Eater\'s Stomach, Room 6 (Gogo)</stri" +
            "ng>\r\n  <string>Zone Eater\'s Stomach, Room 2</string>\r\n  <string>Zone Eater\'s Sto" +
            "mach, Room 3,5</string>\r\n  <string>Narshe, Umaro\'s Cave 1</string>\r\n  <string>Na" +
            "rshe, Umaro\'s Cave 2</string>\r\n  <string>Narshe, Umaro\'s Lair</string>\r\n  <strin" +
            "g>Maranda, Outside (WOR)</string>\r\n  <string>Doma Castle, Outside, Abandoned</st" +
            "ring>\r\n  <string>___nothing</string>\r\n  <string>Kefka\'s Tower, Inside From Guard" +
            "ian</string>\r\n  <string>Maranda, Inn (WOR)</string>\r\n  <string>Maranda, Weapon S" +
            "hop (WOR)</string>\r\n  <string>Maranda, Armor Shop (WOR)</string>\r\n  <string>Kefk" +
            "a\'s Tower, Guardian\'s Room</string>\r\n  <string>Kefka\'s Tower, Junk Room</string>" +
            "\r\n  <string>Kefka\'s Tower, Inside from Factory Room</string>\r\n  <string>Kefka\'s " +
            "Tower, Inside 2</string>\r\n  <string>Kefka\'s Tower, Inside 3</string>\r\n  <string>" +
            "Kefka\'s Tower, Factory Room (Top Level)</string>\r\n  <string>Darill\'s Tomb, Outsi" +
            "de</string>\r\n  <string>Darill\'s Tomb, Basement 1</string>\r\n  <string>Darill\'s To" +
            "mb, Basement 2</string>\r\n  <string>Darill\'s Tomb, Basement 3</string>\r\n  <string" +
            ">Darill\'s Tomb, Staircase</string>\r\n  <string>Ending, Thamasa, Repairing burned " +
            "house</string>\r\n  <string>Kefka\'s Tower, Inside 1</string>\r\n  <string>Kefka\'s To" +
            "wer, Assassin Room</string>\r\n  <string>Tzen, Outside (WOR)</string>\r\n  <string>T" +
            "zen, Outside, Before House Collapse (WOR)</string>\r\n  <string>Tzen, Item Shop (W" +
            "OR)</string>\r\n  <string>Tzen, Inn (WOR)</string>\r\n  <string>Tzen, Weapon Shop (W" +
            "OR)</string>\r\n  <string>Tzen, Armor Shop (WOR)</string>\r\n  <string>Tzen, Inside " +
            "Collapsing House</string>\r\n  <string>Tzen, Relics (WOR)</string>\r\n  <string>Phoe" +
            "nix Cave, Big Lava Room, Drained</string>\r\n  <string>Pheonix Cave, Big Lava Room" +
            "</string>\r\n  <string>Phoenix Cave, Main Room, Drained</string>\r\n  <string>Phoeni" +
            "x Cave, Main Room</string>\r\n  <string>Cyan\'s Dream, Three Stooges</string>\r\n  <s" +
            "tring>Pheonix Cave, Outside Entrance</string>\r\n  <string>Cyan\'s Dream, Magitek C" +
            "aves, Outside</string>\r\n  <string>Cyan\'s Dream, Magitek Caves, Inside</string>\r\n" +
            "  <string>Cyan\'s Dream, Phantom Train, Inside 1</string>\r\n  <string>Cyan\'s Dream" +
            ", Phantom Train, Inside 2</string>\r\n  <string>Albrook, Outside (WOB)</string>\r\n " +
            " <string>Albrook, Outside (WOR)</string>\r\n  <string>Albrook, Inn</string>\r\n  <st" +
            "ring>Albrook, Weapon Shop</string>\r\n  <string>Albrook, Armor Shop</string>\r\n  <s" +
            "tring>Albrook, Item Shop</string>\r\n  <string>Kefka\'s Tower, Room with Movers</st" +
            "ring>\r\n  <string>Albrook, Pub</string>\r\n  <string>Kefka\'s Tower, Atma\'s Room</st" +
            "ring>\r\n  <string>Albrook, Ship Deck</string>\r\n  <string>___Kefka\'s Tower, factor" +
            "y</string>\r\n  <string>Kefka\'s Tower, Outside</string>\r\n  <string>Kefka\'s Tower, " +
            "Gold Dragon Room</string>\r\n  <string>Kefka\'s Tower, Kefka\'s Lair 1</string>\r\n  <" +
            "string>Kefka\'s Tower, 4Ton Switch Room</string>\r\n  <string>Kefka\'s Tower, Inside" +
            " from Central Group</string>\r\n  <string>Kefka\'s Tower, Inside from Eastern Group" +
            "</string>\r\n  <string>Thamasa, Outside, at Leo\'s Grave</string>\r\n  <string>Thamas" +
            "a, Outside, Kefka attacks</string>\r\n  <string>___Thamasa</string>\r\n  <string>Tha" +
            "masa, Outside (WOB)</string>\r\n  <string>Thamasa, Outside (WOR)</string>\r\n  <stri" +
            "ng>Thamasa, Arsenal</string>\r\n  <string>Thamasa, Inn</string>\r\n  <string>Thamasa" +
            ", Item Shop</string>\r\n  <string>Thamasa, Elder\'s House</string>\r\n  <string>Thama" +
            "sa, Strago\'s House</string>\r\n  <string>Thamasa, Relics</string>\r\n  <string>Thama" +
            "sa, Inside Burning House</string>\r\n  <string>Kefka\'s Tower, Broken Capsules</str" +
            "ing>\r\n  <string>Cave in the Veldt (WOR)</string>\r\n  <string>Kefka\'s Tower, Red C" +
            "arpet Rooms</string>\r\n  <string>Kefka\'s Tower, Three Switch Room</string>\r\n  <st" +
            "ring>Kefka\'s Tower, Left Statue Room</string>\r\n  <string>Kefka\'s Tower, Kefka\'s " +
            "Lair 2</string>\r\n  <string>Floating Continent, Save Point</string>\r\n  <string>Fa" +
            "natic\'s Tower, Level 2</string>\r\n  <string>Fanatic\'s Tower, Level 3</string>\r\n  " +
            "<string>Fanatic\'s Tower, Level 4</string>\r\n  <string>Fanatic\'s Tower, Entrance</" +
            "string>\r\n  <string>Fanatic\'s Tower, Level 1</string>\r\n  <string>Fanatic\'s Tower," +
            " Roof</string>\r\n  <string>Fanatic\'s Tower, Treasure Room 2</string>\r\n  <string>F" +
            "anatic\'s Tower, Gem Box Room</string>\r\n  <string>Fanatic\'s Tower, Treasure Room " +
            "3</string>\r\n  <string>Fanatic\'s Tower, Treasure Room 4</string>\r\n  <string>Fanat" +
            "ic\'s Tower, Treasure Room 5</string>\r\n  <string>Fanatic\'s Tower, Treasure Room 1" +
            "</string>\r\n  <string>Esper Cave, Statue Room</string>\r\n  <string>Esper Cave, Out" +
            "side 2</string>\r\n  <string>Esper Cave, Outside 1</string>\r\n  <string>Esper Cave," +
            " Outside 3</string>\r\n  <string>Esper Cave</string>\r\n  <string>Floating Continent" +
            ", Destruction</string>\r\n  <string>Imperial Base</string>\r\n  <string>Imperial Bas" +
            "e, House</string>\r\n  <string>___Imperial Base</string>\r\n  <string>Overhead View " +
            "of World Map</string>\r\n  <string>Mountains Destruction</string>\r\n  <string>Cave " +
            "to the Sealed Gate, Room 1</string>\r\n  <string>Cave to the Sealed Gate, Basement" +
            " 1</string>\r\n  <string>Cave to the Sealed Gate, Basement 3</string>\r\n  <string>C" +
            "ave to the Sealed Gate, Basement 2</string>\r\n  <string>Cave to the Sealed Gate, " +
            "Save Point</string>\r\n  <string>___Cave to the Sealed Gate, Basement 4</string>\r\n" +
            "  <string>___Cave to the Sealed Gate</string>\r\n  <string>Grasslands Destruction<" +
            "/string>\r\n  <string>Highlands Destruction</string>\r\n  <string>Sealed Gate</strin" +
            "g>\r\n  <string>Floating Continent shadow cast above Jidoor</string>\r\n  <string>Fl" +
            "oating Continent, Breaking Apart</string>\r\n  <string>Floating Continent, Outside" +
            "</string>\r\n  <string>Floating Continent Breakaway 1</string>\r\n  <string>Cid\'s Is" +
            "land, Outside</string>\r\n  <string>Cid\'s Island, Inside House</string>\r\n  <string" +
            ">Cid\'s Island, Beach</string>\r\n  <string>Cid\'s Island, Cliff</string>\r\n  <string" +
            ">Cid\'s Island, Beach, no fish</string>\r\n  <string>Ancient Cave 1</string>\r\n  <st" +
            "ring>Ancient Cave 2</string>\r\n  <string>___Cid\'s Island, Beach</string>\r\n  <stri" +
            "ng>Hidon\'s Cave</string>\r\n  <string>Hidon\'s Cave, Entrance</string>\r\n  <string>A" +
            "ncient Castle, Inside</string>\r\n  <string>Ancient Castle, Outside</string>\r\n  <s" +
            "tring>Ancient Castle, Eastern Room</string>\r\n  <string>Kefka\'s Tower, Pipe Room<" +
            "/string>\r\n  <string>Kefka\'s Tower, Factory Room (Bottom Level)</string>\r\n  <stri" +
            "ng>Kefka\'s Tower, Final Room</string>\r\n  <string>Kefka\'s Tower, Guardian Path Sa" +
            "ve Point</string>\r\n  <string>Colosseum</string>\r\n  <string>___</string>\r\n</Array" +
            "OfString>")]
        public global::System.Collections.Specialized.StringCollection LevelNames {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LevelNames"]));
            }
            set {
                this["LevelNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PreviewFirstTime {
            get {
                return ((bool)(this["PreviewFirstTime"]));
            }
            set {
                this["PreviewFirstTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PreviewAssembleLevels {
            get {
                return ((bool)(this["PreviewAssembleLevels"]));
            }
            set {
                this["PreviewAssembleLevels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-m -zs 0 -v 2")]
        public string PreviewArguments {
            get {
                return ((string)(this["PreviewArguments"]));
            }
            set {
                this["PreviewArguments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PreviewDynamicRomName {
            get {
                return ((bool)(this["PreviewDynamicRomName"]));
            }
            set {
                this["PreviewDynamicRomName"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-m -zs 0 -v 2")]
        public string PreviewArgsDefault {
            get {
                return ((string)(this["PreviewArgsDefault"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PreviewEnterEvent {
            get {
                return ((bool)(this["PreviewEnterEvent"]));
            }
            set {
                this["PreviewEnterEvent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZSNESPath {
            get {
                return ((string)(this["ZSNESPath"]));
            }
            set {
                this["ZSNESPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2999423")]
        public int MemoryByte {
            get {
                return ((int)(this["MemoryByte"]));
            }
            set {
                this["MemoryByte"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LevelNamesPath {
            get {
                return ((string)(this["LevelNamesPath"]));
            }
            set {
                this["LevelNamesPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>World of Balance, World Map</string>\r\n  <string>World of Ruin, World Map</" +
            "string>\r\n  <string>Serpent Trench, World Map</string>\r\n  <string>\"On that day..." +
            "\" etc.</string>\r\n  <string>Shadow\'s Dream 1</string>\r\n  <string>Mog\'s Explanatio" +
            "n</string>\r\n  <string>Blackjack, Deck</string>\r\n  <string>Blackjack, Inside</str" +
            "ing>\r\n  <string>Blackjack, Back Room</string>\r\n  <string>Choose A Scenario</stri" +
            "ng>\r\n  <string>Blackjack, Roof</string>\r\n  <string>Falcon, Roof</string>\r\n  <str" +
            "ing>Falcon, Main Room</string>\r\n  <string>Falcon, Roof, Landing on Kefka\'s Tower" +
            "</string>\r\n  <string>Chocobo Stable, Forested (WOB)</string>\r\n  <string>Chocobo " +
            "Stable, Forested Inside</string>\r\n  <string>Chocobo Stable, Forested (WOR)</stri" +
            "ng>\r\n  <string>Falcon, Roof</string>\r\n  <string>Narshe Cliff, Intro</string>\r\n  " +
            "<string>Narshe, Outside, Beginning (WOB)</string>\r\n  <string>Narshe, Outside (WO" +
            "B)</string>\r\n  <string>Narshe, Outside, Beginning (WOB)</string>\r\n  <string>Nars" +
            "he, Outside, Battlefield (WOB)</string>\r\n  <string>Narshe, Outside, Northern Cli" +
            "ff (WOB)</string>\r\n  <string>Narshe, Weapons Shop (WOR)</string>\r\n  <string>Nars" +
            "he, Armor Shop (WOR)</string>\r\n  <string>Narshe, Item Shop (WOR)</string>\r\n  <st" +
            "ring>Narshe, Relics Shop (WOR)</string>\r\n  <string>Narshe, Inn (WOR)</string>\r\n " +
            " <string>Narshe, Pub (WOR)</string>\r\n  <string>Narshe, Elder\'s House</string>\r\n " +
            " <string>___Chocobo Stable</string>\r\n  <string>Narshe, Outside (WOR)</string>\r\n " +
            " <string>Narshe, Outside, North (WOR)</string>\r\n  <string>Narshe, Outside, Battl" +
            "efield (WOR)</string>\r\n  <string>Narshe, Outside, Northern Cliff (WOR)</string>\r" +
            "\n  <string>Narshe, Mines Cart Rail Rooms (WOR)</string>\r\n  <string>Narshe, Mines" +
            " Battle Room (WOR)</string>\r\n  <string>Narshe, Mines 1 (WOR)</string>\r\n  <string" +
            ">Narshe, Outside, North, Beginning</string>\r\n  <string>Narshe, Mines 1, Beginnin" +
            "g (WOB)</string>\r\n  <string>Narshe, Mines 1 (WOB)</string>\r\n  <string>Narshe, Mi" +
            "nes Esper Room, Beginning (WOB)</string>\r\n  <string>Narshe, Mines Esper Room, Em" +
            "pty (WOB)</string>\r\n  <string>Narshe, Moogle\'s Room (WOR)</string>\r\n  <string>__" +
            "_</string>\r\n  <string>___</string>\r\n  <string>___</string>\r\n  <string>Narshe, Mi" +
            "nes 2, From Secret (WOB)</string>\r\n  <string>Narshe, Mines Checkpoint (WOB)</str" +
            "ing>\r\n  <string>Narshe, Mines 2 (WOB)</string>\r\n  <string>Narshe, Mines Battle R" +
            "oom (WOB)</string>\r\n  <string>Narshe, Moogle\'s Room (WOB)</string>\r\n  <string>Ca" +
            "ve to Figaro Castle, Room 2</string>\r\n  <string>Figaro Castle, Submerging</strin" +
            "g>\r\n  <string>Figaro Castle, Outside</string>\r\n  <string>Figaro Desert, Kefka &a" +
            "mp; Troops</string>\r\n  <string>Figaro Castle, King\'s Bedroom</string>\r\n  <string" +
            ">Figaro Castle, Throne Room</string>\r\n  <string>Figaro Castle, Inside</string>\r\n" +
            "  <string>Figaro Castle, Library</string>\r\n  <string>Figaro Castle, Basement 1</" +
            "string>\r\n  <string>Figaro Castle, Basement 2</string>\r\n  <string>Figaro Castle, " +
            "Basement 3</string>\r\n  <string>Figaro Castle, Engine Room</string>\r\n  <string>Fi" +
            "garo Castle, Treasure Room</string>\r\n  <string>Figaro Castle, Regal Crown Room</" +
            "string>\r\n  <string>Figaro Castle, Outside, Nighttime</string>\r\n  <string>Cave to" +
            " South Figaro (WOR)</string>\r\n  <string>Cave to South Figaro, Rooms</string>\r\n  " +
            "<string>Cave to South Figaro (WOB)</string>\r\n  <string>Cave to South Figaro, Ent" +
            "rance</string>\r\n  <string>Cave to South Figaro, Room 2</string>\r\n  <string>Cave " +
            "to South Figaro, Room 1</string>\r\n  <string>South Figaro, Outside (WOR)</string>" +
            "\r\n  <string>South Figaro, Outside (WOB)</string>\r\n  <string>South Figaro, Inn/Re" +
            "lics</string>\r\n  <string>South Figaro, Arsenal</string>\r\n  <string>South Figaro," +
            " Pub</string>\r\n  <string>___</string>\r\n  <string>South Figaro, Chocobo Stable</s" +
            "tring>\r\n  <string>South Figaro, Rich Man\'s House</string>\r\n  <string>___</string" +
            ">\r\n  <string>South Figaro, Basement 1</string>\r\n  <string>South Figaro, Basement" +
            " 1 Clock Room</string>\r\n  <string>South Figaro, Item Shop</string>\r\n  <string>So" +
            "uth Figaro, Duncan\'s House</string>\r\n  <string>South Figaro, Basement 1 Monster " +
            "Room</string>\r\n  <string>South Figaro, Basement 1 Save Point</string>\r\n  <string" +
            ">South Figaro, Basement 2</string>\r\n  <string>Cave to Figaro Castle, Entrance (W" +
            "OR)</string>\r\n  <string>South Figaro, Dock (WOR)</string>\r\n  <string>Cave to Fig" +
            "aro Castle, Room 1</string>\r\n  <string>Sabin\'s House, Outside</string>\r\n  <strin" +
            "g>Sabin\'s House, Inside</string>\r\n  <string>Mt.Kolts, Entrance</string>\r\n  <stri" +
            "ng>Mt.Kolts, Outside</string>\r\n  <string>Mt.Kolts, Outside Bridge</string>\r\n  <s" +
            "tring>Mt.Kolts, Outside Vargas Area</string>\r\n  <string>___</string>\r\n  <string>" +
            "Mt.Kolts, Cave</string>\r\n  <string>Mt.Kolts, Exit</string>\r\n  <string>Mt.Kolts, " +
            "Cliffs</string>\r\n  <string>Mt.Kolts, Cave Save Point</string>\r\n  <string>Narshe," +
            " School</string>\r\n  <string>Narshe, School, Adv. Battle Tactics</string>\r\n  <str" +
            "ing>Narshe, School, Battle Tactics</string>\r\n  <string>Narshe, School, Environme" +
            "ntal Science</string>\r\n  <string>Returner\'s Hideout, Entrance</string>\r\n  <strin" +
            "g>Returner\'s Hideout, Inside</string>\r\n  <string>Returner\'s Hideout, Rooms</stri" +
            "ng>\r\n  <string>Returner\'s Hideout, Inn</string>\r\n  <string>Tunnel to Lete River<" +
            "/string>\r\n  <string>Lete River</string>\r\n  <string>Lete River Cave</string>\r\n  <" +
            "string>Gau\'s Father\'s House, Outside</string>\r\n  <string>Gau\'s Father\'s House, I" +
            "nside</string>\r\n  <string>Military Base Camp</string>\r\n  <string>___</string>\r\n " +
            " <string>Military Base Camp 2</string>\r\n  <string>Doma Castle, Outside (WOB)</st" +
            "ring>\r\n  <string>Doma Castle, Outside Poisoning (WOB)</string>\r\n  <string>___</s" +
            "tring>\r\n  <string>Doma Castle, Inside</string>\r\n  <string>Doma Castle, Cyan\'s Ro" +
            "om</string>\r\n  <string>Cyan\'s Dream, Doma Castle, Outside</string>\r\n  <string>Cy" +
            "an\'s Dream, Doma Castle Rooms</string>\r\n  <string>Duncan\'s House, Outside</strin" +
            "g>\r\n  <string>Duncan\'s House, Inside</string>\r\n  <string>Ending, sky with birds<" +
            "/string>\r\n  <string>Ending, Phantom Forest</string>\r\n  <string>Gau\'s Father\'s Ho" +
            "use, Outside (WOR)</string>\r\n  <string>Phantom Forest 1</string>\r\n  <string>Phan" +
            "tom Forest 2</string>\r\n  <string>Phantom Forest 3</string>\r\n  <string>Phantom Fo" +
            "rest 4</string>\r\n  <string>Ending, mountain bridge</string>\r\n  <string>Phantom T" +
            "rain, Docking Station 4</string>\r\n  <string>Phantom Train, Docking Station 2</st" +
            "ring>\r\n  <string>Phantom Train, Docking Station 3</string>\r\n  <string>Phantom Tr" +
            "ain, Docking Station 1</string>\r\n  <string>Phantom Train, Outside 2</string>\r\n  " +
            "<string>Phantom Train, Outside 1</string>\r\n  <string>Cyan\'s Dream, Phantom Train" +
            ", Outside</string>\r\n  <string>Cyan\'s Dream, Phantom Train, Inside</string>\r\n  <s" +
            "tring>Phantom Train, Inside 1</string>\r\n  <string>Phantom Train, Engineer\'s Room" +
            "</string>\r\n  <string>Phantom Train, Restaurant</string>\r\n  <string>Mobliz, Outsi" +
            "de during Light of Judgement</string>\r\n  <string>Phantom Train, Inside 2</string" +
            ">\r\n  <string>Mobliz, Basement 2, After Phunbaba 1</string>\r\n  <string>Phantom Tr" +
            "ain, Inside 3</string>\r\n  <string>Phantom Train, Inside 4</string>\r\n  <string>Ph" +
            "antom Train, Inside Rooms</string>\r\n  <string>Mobliz, Basement 2</string>\r\n  <st" +
            "ring>Waterfall Cave</string>\r\n  <string>Waterfall Cliff</string>\r\n  <string>Mobl" +
            "iz, Outside (WOB)</string>\r\n  <string>Mobliz, Outside (WOR)</string>\r\n  <string>" +
            "Veldt Shore</string>\r\n  <string>Mobliz, Inn</string>\r\n  <string>Mobliz, Arsenal<" +
            "/string>\r\n  <string>Mobliz, Relics</string>\r\n  <string>Mobliz, Mail House</strin" +
            "g>\r\n  <string>Mobliz, Item Shop</string>\r\n  <string>Mobliz, Basement 1</string>\r" +
            "\n  <string>Waterfall Entrance</string>\r\n  <string>Veldt Cave to Waterfall</strin" +
            "g>\r\n  <string>Veldt Waterfall</string>\r\n  <string>Nikeah, Outside</string>\r\n  <s" +
            "tring>Veldt Shore</string>\r\n  <string>Nikeah, Inn</string>\r\n  <string>Nikeah, Pu" +
            "b</string>\r\n  <string>Nikeah, Chocobo Stable</string>\r\n  <string>Shadow\'s Dream " +
            "2, Phantom Forest</string>\r\n  <string>Serpent Trench Cave 1</string>\r\n  <string>" +
            "Mt.Zozo, Outside Bridge</string>\r\n  <string>Mt.Zozo, Outside 1</string>\r\n  <stri" +
            "ng>Mt.Zozo, Outside 2</string>\r\n  <string>Mt.Zozo, Inside</string>\r\n  <string>Mt" +
            ".Zozo, Cyan\'s Room</string>\r\n  <string>Mt.Zozo, Cliff</string>\r\n  <string>Ending" +
            ", Relm, Shadow, Strago</string>\r\n  <string>Mobliz, Basement 2, Before Kefka Figh" +
            "t</string>\r\n  <string>Mobliz, Outside, Before Kefka Fight</string>\r\n  <string>Cr" +
            "azy Man\'s House, Outside</string>\r\n  <string>Crazy Man\'s House, Inside</string>\r" +
            "\n  <string>Nikeah, Ferry (WOB)</string>\r\n  <string>Kohlingen, Outside (WOB)</str" +
            "ing>\r\n  <string>Kohlingen, Outside (WOR)</string>\r\n  <string>Ending, Rapids</str" +
            "ing>\r\n  <string>Kohlingen, Inn (WOR)</string>\r\n  <string>___Kohlingen</string>\r\n" +
            "  <string>___Kohlingen, Arsenal</string>\r\n  <string>Kohlingen, General Store</st" +
            "ring>\r\n  <string>Kohlingen, Chemist\'s House</string>\r\n  <string>Maranda, Flower " +
            "Girl\'s House (WOR)</string>\r\n  <string>Kohlingen, Rachel\'s House</string>\r\n  <st" +
            "ring>Jidoor, Outside</string>\r\n  <string>___nothing</string>\r\n  <string>Jidoor, " +
            "Auction House</string>\r\n  <string>Jidoor, Item Shop</string>\r\n  <string>Jidoor, " +
            "Relics</string>\r\n  <string>Jidoor, Armor Shop</string>\r\n  <string>Jidoor, Weapon" +
            " Shop</string>\r\n  <string>Jidoor, Chocobo Stable</string>\r\n  <string>Jidoor, Inn" +
            "</string>\r\n  <string>Owzer\'s House, Basement</string>\r\n  <string>Owzer\'s House, " +
            "Art Room</string>\r\n  <string>Owzer\'s House, F1</string>\r\n  <string>Ending, Cyan " +
            "1</string>\r\n  <string>Ending, Umaro, Mog 1</string>\r\n  <string>Ending, Gogo 1</s" +
            "tring>\r\n  <string>Ending, Gau 1</string>\r\n  <string>Cliff, Setzer waits for Dari" +
            "ll</string>\r\n  <string>Ending, Falcon flying through sky</string>\r\n  <string>Esp" +
            "er World, Lake</string>\r\n  <string>Esper World, Outside</string>\r\n  <string>Espe" +
            "r World, Gate</string>\r\n  <string>Esper World, House</string>\r\n  <string>___boat" +
            " dock</string>\r\n  <string>Zozo, Outside</string>\r\n  <string>___nothing</string>\r" +
            "\n  <string>___nothing</string>\r\n  <string>___nothing</string>\r\n  <string>Zozo, I" +
            "nside House</string>\r\n  <string>Zozo, Terra\'s Room</string>\r\n  <string>___nothin" +
            "g</string>\r\n  <string>___nothing</string>\r\n  <string>___nothing</string>\r\n  <str" +
            "ing>___nothing</string>\r\n  <string>Opera House, Theater</string>\r\n  <string>Oper" +
            "a House, Switch Room</string>\r\n  <string>Opera House, Theater Play 2</string>\r\n " +
            " <string>Opera House, Theater Play 1</string>\r\n  <string>Opera House, Ceiling</s" +
            "tring>\r\n  <string>Opera House, Castle Balcony</string>\r\n  <string>Opera House, M" +
            "ain</string>\r\n  <string>Opera House, Dressing Room</string>\r\n  <string>___Opera " +
            "House</string>\r\n  <string>Vector, after Magitek Factory</string>\r\n  <string>Impe" +
            "rial Castle, Cranes Activating</string>\r\n  <string>Vector, Outside</string>\r\n  <" +
            "string>Imperial Castle</string>\r\n  <string>Imperial Castle, Outside Roof</string" +
            ">\r\n  <string>Vector, Inn</string>\r\n  <string>Vector, Weapon Shop</string>\r\n  <st" +
            "ring>Vector, Pub</string>\r\n  <string>Vector, Armor Shop</string>\r\n  <string>Vect" +
            "or, Healer\'s House</string>\r\n  <string>Imperial Castle, Inside</string>\r\n  <stri" +
            "ng>Imperial Castle, Banquet</string>\r\n  <string>Imperial Castle, Bedroom</string" +
            ">\r\n  <string>Vector, Outside, Burning</string>\r\n  <string>Ending, Cyan, Mog, Gog" +
            "o 2</string>\r\n  <string>Ending, Setzer</string>\r\n  <string>Ending, Umaro 2</stri" +
            "ng>\r\n  <string>___Magitek Factory</string>\r\n  <string>Ending, Edgar and Sabin</s" +
            "tring>\r\n  <string>Ending, Falcon taking flight from Kefka\'s Tower</string>\r\n  <s" +
            "tring>Ending, Locke and Celes 1</string>\r\n  <string>Ending, Shadow, Strago, Gau " +
            "2</string>\r\n  <string>Magitek Factory, Room 1</string>\r\n  <string>Magitek Factor" +
            "y, Room 2</string>\r\n  <string>Magitek Factory, Room 3 (Espers)</string>\r\n  <stri" +
            "ng>___Magitek Factory</string>\r\n  <string>Magitek Factory, Elevator</string>\r\n  " +
            "<string>___Magitek Factory</string>\r\n  <string>Ending, Terra</string>\r\n  <string" +
            ">Magitek Factory, Room 4</string>\r\n  <string>Magitek Factory, Room 5 (Save)</str" +
            "ing>\r\n  <string>Magitek Res. Facility, Room 1</string>\r\n  <string>Magitek Factor" +
            "y, Minecart Dock</string>\r\n  <string>Magitek Res. Facility, Room 2 (Number 042)<" +
            "/string>\r\n  <string>Magitek Res. Facility, Espers</string>\r\n  <string>___dummied" +
            "</string>\r\n  <string>Zone Eater\'s Stomach, Room 1</string>\r\n  <string>Zone Eater" +
            "\'s Stomach, Room 4</string>\r\n  <string>Zone Eater\'s Stomach, Room 6 (Gogo)</stri" +
            "ng>\r\n  <string>Zone Eater\'s Stomach, Room 2</string>\r\n  <string>Zone Eater\'s Sto" +
            "mach, Room 3,5</string>\r\n  <string>Narshe, Umaro\'s Cave 1</string>\r\n  <string>Na" +
            "rshe, Umaro\'s Cave 2</string>\r\n  <string>Narshe, Umaro\'s Lair</string>\r\n  <strin" +
            "g>Maranda, Outside (WOR)</string>\r\n  <string>Doma Castle, Outside, Abandoned</st" +
            "ring>\r\n  <string>___nothing</string>\r\n  <string>Kefka\'s Tower, Inside From Guard" +
            "ian</string>\r\n  <string>Maranda, Inn (WOR)</string>\r\n  <string>Maranda, Weapon S" +
            "hop (WOR)</string>\r\n  <string>Maranda, Armor Shop (WOR)</string>\r\n  <string>Kefk" +
            "a\'s Tower, Guardian\'s Room</string>\r\n  <string>Kefka\'s Tower, Junk Room</string>" +
            "\r\n  <string>Kefka\'s Tower, Inside from Factory Room</string>\r\n  <string>Kefka\'s " +
            "Tower, Inside 2</string>\r\n  <string>Kefka\'s Tower, Inside 3</string>\r\n  <string>" +
            "Kefka\'s Tower, Factory Room (Top Level)</string>\r\n  <string>Darill\'s Tomb, Outsi" +
            "de</string>\r\n  <string>Darill\'s Tomb, Basement 1</string>\r\n  <string>Darill\'s To" +
            "mb, Basement 2</string>\r\n  <string>Darill\'s Tomb, Basement 3</string>\r\n  <string" +
            ">Darill\'s Tomb, Staircase</string>\r\n  <string>Ending, Thamasa, Repairing burned " +
            "house</string>\r\n  <string>Kefka\'s Tower, Inside 1</string>\r\n  <string>Kefka\'s To" +
            "wer, Assassin Room</string>\r\n  <string>Tzen, Outside (WOR)</string>\r\n  <string>T" +
            "zen, Outside, Before House Collapse (WOR)</string>\r\n  <string>Tzen, Item Shop (W" +
            "OR)</string>\r\n  <string>Tzen, Inn (WOR)</string>\r\n  <string>Tzen, Weapon Shop (W" +
            "OR)</string>\r\n  <string>Tzen, Armor Shop (WOR)</string>\r\n  <string>Tzen, Inside " +
            "Collapsing House</string>\r\n  <string>Tzen, Relics (WOR)</string>\r\n  <string>Phoe" +
            "nix Cave, Big Lava Room, Drained</string>\r\n  <string>Pheonix Cave, Big Lava Room" +
            "</string>\r\n  <string>Phoenix Cave, Main Room, Drained</string>\r\n  <string>Phoeni" +
            "x Cave, Main Room</string>\r\n  <string>Cyan\'s Dream, Three Stooges</string>\r\n  <s" +
            "tring>Pheonix Cave, Outside Entrance</string>\r\n  <string>Cyan\'s Dream, Magitek C" +
            "aves, Outside</string>\r\n  <string>Cyan\'s Dream, Magitek Caves, Inside</string>\r\n" +
            "  <string>Cyan\'s Dream, Phantom Train, Inside 1</string>\r\n  <string>Cyan\'s Dream" +
            ", Phantom Train, Inside 2</string>\r\n  <string>Albrook, Outside (WOB)</string>\r\n " +
            " <string>Albrook, Outside (WOR)</string>\r\n  <string>Albrook, Inn</string>\r\n  <st" +
            "ring>Albrook, Weapon Shop</string>\r\n  <string>Albrook, Armor Shop</string>\r\n  <s" +
            "tring>Albrook, Item Shop</string>\r\n  <string>Kefka\'s Tower, Room with Movers</st" +
            "ring>\r\n  <string>Albrook, Pub</string>\r\n  <string>Kefka\'s Tower, Atma\'s Room</st" +
            "ring>\r\n  <string>Albrook, Ship Deck</string>\r\n  <string>___Kefka\'s Tower, factor" +
            "y</string>\r\n  <string>Kefka\'s Tower, Outside</string>\r\n  <string>Kefka\'s Tower, " +
            "Gold Dragon Room</string>\r\n  <string>Kefka\'s Tower, Kefka\'s Lair 1</string>\r\n  <" +
            "string>Kefka\'s Tower, 4Ton Switch Room</string>\r\n  <string>Kefka\'s Tower, Inside" +
            " from Central Group</string>\r\n  <string>Kefka\'s Tower, Inside from Eastern Group" +
            "</string>\r\n  <string>Thamasa, Outside, at Leo\'s Grave</string>\r\n  <string>Thamas" +
            "a, Outside, Kefka attacks</string>\r\n  <string>___Thamasa</string>\r\n  <string>Tha" +
            "masa, Outside (WOB)</string>\r\n  <string>Thamasa, Outside (WOR)</string>\r\n  <stri" +
            "ng>Thamasa, Arsenal</string>\r\n  <string>Thamasa, Inn</string>\r\n  <string>Thamasa" +
            ", Item Shop</string>\r\n  <string>Thamasa, Elder\'s House</string>\r\n  <string>Thama" +
            "sa, Strago\'s House</string>\r\n  <string>Thamasa, Relics</string>\r\n  <string>Thama" +
            "sa, Inside Burning House</string>\r\n  <string>Kefka\'s Tower, Broken Capsules</str" +
            "ing>\r\n  <string>Cave in the Veldt (WOR)</string>\r\n  <string>Kefka\'s Tower, Red C" +
            "arpet Rooms</string>\r\n  <string>Kefka\'s Tower, Three Switch Room</string>\r\n  <st" +
            "ring>Kefka\'s Tower, Left Statue Room</string>\r\n  <string>Kefka\'s Tower, Kefka\'s " +
            "Lair 2</string>\r\n  <string>Floating Continent, Save Point</string>\r\n  <string>Fa" +
            "natic\'s Tower, Level 2</string>\r\n  <string>Fanatic\'s Tower, Level 3</string>\r\n  " +
            "<string>Fanatic\'s Tower, Level 4</string>\r\n  <string>Fanatic\'s Tower, Entrance</" +
            "string>\r\n  <string>Fanatic\'s Tower, Level 1</string>\r\n  <string>Fanatic\'s Tower," +
            " Roof</string>\r\n  <string>Fanatic\'s Tower, Treasure Room 2</string>\r\n  <string>F" +
            "anatic\'s Tower, Gem Box Room</string>\r\n  <string>Fanatic\'s Tower, Treasure Room " +
            "3</string>\r\n  <string>Fanatic\'s Tower, Treasure Room 4</string>\r\n  <string>Fanat" +
            "ic\'s Tower, Treasure Room 5</string>\r\n  <string>Fanatic\'s Tower, Treasure Room 1" +
            "</string>\r\n  <string>Esper Cave, Statue Room</string>\r\n  <string>Esper Cave, Out" +
            "side 2</string>\r\n  <string>Esper Cave, Outside 1</string>\r\n  <string>Esper Cave," +
            " Outside 3</string>\r\n  <string>Esper Cave</string>\r\n  <string>Floating Continent" +
            ", Destruction</string>\r\n  <string>Imperial Base</string>\r\n  <string>Imperial Bas" +
            "e, House</string>\r\n  <string>___Imperial Base</string>\r\n  <string>Overhead View " +
            "of World Map</string>\r\n  <string>Mountains Destruction</string>\r\n  <string>Cave " +
            "to the Sealed Gate, Room 1</string>\r\n  <string>Cave to the Sealed Gate, Basement" +
            " 1</string>\r\n  <string>Cave to the Sealed Gate, Basement 3</string>\r\n  <string>C" +
            "ave to the Sealed Gate, Basement 2</string>\r\n  <string>Cave to the Sealed Gate, " +
            "Save Point</string>\r\n  <string>___Cave to the Sealed Gate, Basement 4</string>\r\n" +
            "  <string>___Cave to the Sealed Gate</string>\r\n  <string>Grasslands Destruction<" +
            "/string>\r\n  <string>Highlands Destruction</string>\r\n  <string>Sealed Gate</strin" +
            "g>\r\n  <string>Floating Continent shadow cast above Jidoor</string>\r\n  <string>Fl" +
            "oating Continent, Breaking Apart</string>\r\n  <string>Floating Continent, Outside" +
            "</string>\r\n  <string>Floating Continent Breakaway 1</string>\r\n  <string>Cid\'s Is" +
            "land, Outside</string>\r\n  <string>Cid\'s Island, Inside House</string>\r\n  <string" +
            ">Cid\'s Island, Beach</string>\r\n  <string>Cid\'s Island, Cliff</string>\r\n  <string" +
            ">Cid\'s Island, Beach, no fish</string>\r\n  <string>Ancient Cave 1</string>\r\n  <st" +
            "ring>Ancient Cave 2</string>\r\n  <string>___Cid\'s Island, Beach</string>\r\n  <stri" +
            "ng>Hidon\'s Cave</string>\r\n  <string>Hidon\'s Cave, Entrance</string>\r\n  <string>A" +
            "ncient Castle, Inside</string>\r\n  <string>Ancient Castle, Outside</string>\r\n  <s" +
            "tring>Ancient Castle, Eastern Room</string>\r\n  <string>Kefka\'s Tower, Pipe Room<" +
            "/string>\r\n  <string>Kefka\'s Tower, Factory Room (Bottom Level)</string>\r\n  <stri" +
            "ng>Kefka\'s Tower, Final Room</string>\r\n  <string>Kefka\'s Tower, Guardian Path Sa" +
            "ve Point</string>\r\n  <string>Colosseum</string>\r\n  <string>___</string>\r\n  <stri" +
            "ng>New Map</string>\r\n  <string>New Map</string>\r\n  <string>New Map</string>\r\n  <" +
            "string>New Map</string>\r\n  <string>New Map</string>\r\n  <string>New Map</string>\r" +
            "\n  <string>New Map</string>\r\n  <string>New Map</string>\r\n  <string>New Map</stri" +
            "ng>\r\n  <string>New Map</string>\r\n  <string>New Map</string>\r\n  <string>New Map</" +
            "string>\r\n  <string>New Map</string>\r\n  <string>New Map</string>\r\n  <string>New M" +
            "ap</string>\r\n  <string>New Map</string>\r\n  <string>New Map</string>\r\n  <string>N" +
            "ew Map</string>\r\n  <string>New Map</string>\r\n  <string>New Map</string>\r\n  <stri" +
            "ng>New Map</string>\r\n  <string>New Map</string>\r\n  <string>New Map</string>\r\n  <" +
            "string>New Map</string>\r\n  <string>New Map</string>\r\n  <string>New Map</string>\r" +
            "\n  <string>New Map</string>\r\n  <string>New Map</string>\r\n  <string>New Map</stri" +
            "ng>\r\n  <string>New Map</string>\r\n  <string>New Map</string>\r\n  <string>New Map</" +
            "string>\r\n  <string>New Map</string>\r\n  <string>New Map</string>\r\n  <string>New M" +
            "ap</string>\r\n  <string>New Map</string>\r\n  <string>New Map</string>\r\n  <string>N" +
            "ew Map</string>\r\n  <string>New Map</string>\r\n  <string>New Map</string>\r\n  <stri" +
            "ng>New Map</string>\r\n  <string>New Map</string>\r\n  <string>New Map</string>\r\n  <" +
            "string>New Map</string>\r\n  <string>New Map</string>\r\n  <string>New Map</string>\r" +
            "\n  <string>New Map</string>\r\n  <string>New Map</string>\r\n  <string>New Map</stri" +
            "ng>\r\n  <string>New Map</string>\r\n  <string>New Map</string>\r\n  <string>New Map</" +
            "string>\r\n  <string>New Map</string>\r\n  <string>New Map</string>\r\n  <string>New M" +
            "ap</string>\r\n  <string>New Map</string>\r\n  <string>New Map</string>\r\n  <string>N" +
            "ew Map</string>\r\n  <string>New Map</string>\r\n  <string>New Map</string>\r\n  <stri" +
            "ng>New Map</string>\r\n  <string>New Map</string>\r\n  <string>New Map</string>\r\n  <" +
            "string>New Map</string>\r\n  <string>New Map</string>\r\n  <string>New Map</string>\r" +
            "\n  <string>New Map</string>\r\n  <string>New Map</string>\r\n  <string>New Map</stri" +
            "ng>\r\n  <string>New Map</string>\r\n  <string>New Map</string>\r\n  <string>New Map</" +
            "string>\r\n  <string>New Map</string>\r\n  <string>New Map</string>\r\n  <string>New M" +
            "ap</string>\r\n  <string>New Map</string>\r\n  <string>New Map</string>\r\n  <string>N" +
            "ew Map</string>\r\n  <string>New Map</string>\r\n  <string>New Map</string>\r\n  <stri" +
            "ng>New Map</string>\r\n  <string>New Map</string>\r\n  <string>New Map</string>\r\n  <" +
            "string>New Map</string>\r\n  <string>New Map</string>\r\n  <string>New Map</string>\r" +
            "\n  <string>New Map</string>\r\n  <string>New Map</string>\r\n  <string>New Map</stri" +
            "ng>\r\n  <string>New Map</string>\r\n  <string>New Map</string>\r\n  <string>New Map</" +
            "string>\r\n  <string>New Map</string>\r\n  <string>New Map</string>\r\n  <string>New M" +
            "ap</string>\r\n  <string>New Map</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ExpandedLevelNames {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ExpandedLevelNames"]));
            }
            set {
                this["ExpandedLevelNames"] = value;
            }
        }
    }
}
